<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $text
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
?>

<h2><?= $escape($translate('Site under maintenance')) ?></h2>
<?php if (empty($text)): ?>
<p><?= $escape($translate('This site is down for maintenance. Please contact the site administrator for more information.')) ?></p>
<?php else: ?>
<?= $translate($text) ?>
<?php endif; ?>
