<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$uploadLimit = $plugins->get('uploadLimit');

// This form may be called directly, so prepare it manually.
$services = @$plugins->getServiceLocator();
$config = $services->get('Config');
$settings = $services->get('Omeka\Settings');

$allowedMediaTypes = array_unique(array_merge(
    $config['api_assets']['allowed_media_types'] ?? [],
    $settings->get('easyadmin_asset_media_types', []) ?: []
));
$allowedExtensions = array_unique(array_merge(
    $config['api_assets']['allowed_extensions'] ?? [],
    $settings->get('easyadmin_asset_extensions', []) ?: []
));

$accept = implode(',', array_merge(
    $allowedMediaTypes,
    array_map(fn ($ext) => '.' . ltrim($ext, '.'), $allowedExtensions)
));
?>

<h3 id="asset-upload-label"><?= $escape($translate('Upload new asset')) ?></h3>
<form class="asset-upload" method="post" enctype="multipart/form-data" action="<?= $escapeAttr($url('admin/default', ['controller' => 'asset', 'action' => 'add'])) ?>">
    <input type="file" name="file" accept="<?= $escapeAttr($accept) ?>" required="required" aria-labelledby="asset-upload-label"/>
    <span><?= $uploadLimit() ?></span>
    <label for="asset-upload-alt-text"><?= $escape($translate('Alt text')) ?></label>
    <textarea id="asset-upload-alt-text" name="o:alt_text"></textarea>
    <label for="optimize">
        <input type="checkbox" name="optimize" id="optimize" value="1"/>
        <?= $escape($translate('Optimize size for web (may degrade quality)')) ?>
    </label>
    <label for="store_original_name">
        <input type="checkbox" name="store_original_name" id="store_original_name" value="1"/>
        <?= $escape($translate('Store and serve with original name')) ?>
    </label>
    <button type="submit" class="button"><?= $escape($translate('Upload')) ?></button>
    <ul class="errors"></ul>
</form>
