<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $data
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$htmlAttributes = $plugins->get('htmlAttributes');

$this->headLink()
    ->appendStylesheet($assetUrl('css/bulk-upload.css', 'EasyAdmin'));
$this->headScript()
    ->appendFile($assetUrl('vendor/flow.js/flow.min.js', 'EasyAdmin'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/bulk-upload.js', 'EasyAdmin'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'easy-admin bulk-uploads');
?>

<?= $this->pageTitle($translate('Upload files'), 1, $translate('Easy Admin')) ?>

<p>
    <?= sprintf(
        $translate('Upload files without size or number limitation and without direct access to server, for example for %1$sFile Sideload%2$s or %3$sBulk Import%2$s. All uploaded files will be stored directly at the root of the configured directory.'),
        '<a href="https://omeka.org/s/modules/FileSideload/" target="_blank">', '</a>', '<a href="https://omeka.org/s/modules/BulkImport" target="_blank">') ?>
</p>

<p>
    <?= sprintf($translate('%1$sWarning%2$s: existing files with the same name than uploaded files will be overridden.'), '<strong>', '</strong>') ?>
</p>

<div id="bulk-upload" class="media-field-wrapper">
    <div class="field media-bulk-upload" data-main-index="__index__" <?= $htmlAttributes($data) ?>>
        <div class="field field-drag-and-drop">
            <div class="inputs bulk-drop">
                <span><?= $escape($translate('Drag and drop')) ?></span>
            </div>
        </div>
        <div class="field field-browse-files">
            <div class="inputs">
                <button type="button" class="button-browse button-browse-files"><?= $escape($translate('Browse files')) ?></button>
            </div>
        </div>
        <div class="field field-browse-folders">
            <div class="inputs">
                <button type="button" class="button-browse button-browse-directory" webkitdirectory="webkitdirectory"><?= $escape($translate('Select directory')) ?></button>
            </div>
        </div>
    </div>
    <input type="hidden" name="filesData[file][__index__]" value="[]" class="filesdata"/>
    <div class="field bulk-upload-actions-pre empty">
        <div class="bulk-upload-actions-more">
            <label class="hide-upload-label">
                <input type="checkbox" class="hide-uploaded" name="hide-uploaded"/>
                <span><?= $escape($translate('Hide uploaded files')) ?></span>
            </label>
        </div>
        <div class="bulk-upload-actions-button">
            <button type="button" class="button-pause"><?= $escape($data['data-translate-pause']) ?></button>
        </div>
        <div class="media-files-input-full-progress">
            <div class="progress-count">
                <span class="progress-current"></span> / <span class="progress-total"></span>
            </div>
            <span class="progress-wait"><?= $escape($translate('Uploading in progress…')) ?></span>
        </div>
    </div>
    <div class="field bulk-upload-actions">
    </div>
    <div class="field media-files-input-preview"><ol></ol></div>
</div>
