<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \EasyAdmin\Form\AddonsForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$form->prepare();

$this->headLink()
    ->appendStylesheet($assetUrl('css/easy-admin.css', 'EasyAdmin'));

$this->htmlElement('body')->appendAttribute('class', 'easy-admin easy-admin-addons');
?>

<?= $this->pageTitle($translate('Install addons'), 1, $translate('Easy Admin')) ?>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\EasyAdmin')->menu() ?>
</nav>

<p class="explanation">
    <?= sprintf($translate('For more information on addons, see the pages %smodules%s and %sthemes%s or on %sOmeka.org%s.'),
        '<a href="https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_modules.html" rel="noopener" target="_blank">', '</a>',
        '<a href="https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_themes.html" rel="noopener" target="_blank">', '</a>',
        '<a href="https://omeka.org/s" rel="noopener" target="_blank">', '</a>') ?>
</p>

<p class="explanation">
    <?= $translate('Select either a module, a theme or a selection. Only one choice can be submitted at a time.') ?>
    <?= $translate('Addons with an asterisk are already downloaded.') ?>
</p>

<p class="explanation">
    <?= sprintf($translate('See the details of the %1$scurated selections of modules%2$s.'),
        '<a href="https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_selections.html" rel="noopener" target="_blank">', '</a>') ?>
</p>

<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <input type="submit" name="upload" value="<?= $escape($translate('Submit')) ?>">
</div>

<?= $this->formCollection($form, false) ?>

<?= $this->form()->closeTag($form) ?>
