<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \EasyAdmin\Form\JobsForm $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$form->prepare();

$this->htmlElement('body')->appendAttribute('class', 'easy-admin bulk-check browse');
?>

<?= $this->pageTitle($translate('Check and fixes'), 1, $translate('Easy Admin')) ?>

<h2><?= $escape($translate('Checks and fixes')) ?></h2>
<?= $this->form()->openTag($form) ?>
<div id="page-actions">
    <button type="submit"><?= $translate('Submit') ?></button>
</div>
<?= $this->formCollection($form) ?>
<?= $this->form()->closeTag() ?>
