<?php
use Omeka\Stdlib\Message;

$form->prepare();
$escapeHtml = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Easy Install')); ?>
<p class="explanation">
    <?php echo $this->translate(new Message('For more information on addons, see the pages %smodules%s and %sthemes%s.',
        '<a href="https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_modules.html">', '</a>',
        '<a href="https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_themes.html">', '</a>')); ?>
</p>
<p class="explanation">
    <?php echo $this->translate('Select either a module or a theme.'); ?>
    <?php echo $this->translate('Addons with an asterisk are already downloaded.'); ?>
</p>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form, false); ?>
<fieldset id='upload'>
    <button type="submit"><?php echo $this->translate('Upload'); ?></button>
</fieldset>
<?php echo $this->form()->closeTag($form); ?>
