<?php
$form->prepare();
$escapeHtml = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Easy Install')); ?>
<p class="explanation">
    <?php echo $this->translate('Addons with an asterisk are already downloaded.'); ?>
</p>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form, false); ?>
<fieldset id='upload'>
    <button type="submit"><?php echo $this->translate('Upload'); ?></button>
</fieldset>
<?php echo $this->form()->closeTag($form); ?>
